{{- if eq (include "agent.agentScripts" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-agent-scripts
  labels:
    k8s-app: {{ .Release.Name }}
    type: agent-scripts
    version: v1
data:
  agent-lapi-register.sh: |-
{{ (.Files.Get "files/agent-lapi-register.sh") | indent 4 }}
  agent-start.sh: |-
{{ (.Files.Get "files/agent-start.sh") | indent 4 }}
{{- end }}
